name: "🐛 Write Blog"
description: Create a new post.
title: "<title>"
labels: [
  "post"
]
body:
  - type: dropdown
    id: categories
    attributes:
      label: "Categories"
      description: What categories are the post on?
      multiple: true
      options:
        - Bug
    validations:
      required: true
  - type: textarea
    id: Content
    attributes:
      label: "Content"
      description: Please write some content
      placeholder: post content...
    validations:
      required: true
  - type: dropdown
    id: tags
    attributes:
      label: "Tags"
      description: What is the tags?
      multiple: true
      options:
        - Linux
        - Shell
    validations:
      required: true